import {describe,it,expect} from 'vitest';import {mayaCalendar,sexagenary,chineseCalendar,egyptCalendar,EGYPT_EPOCH,hexagramLines,birthJD} from '../modules/calendars';import {panchanga,ayanamsa} from '../modules/panchanga';import {calculateModule} from '../modules/registry';import {tibetanProvider,hanProvider} from '../modules/contracts';import {defaults,moduleIds} from '../core/state';import {toJD} from '../core/time';import {longitudes,solarContext,nextPhase,lunarMechanical,LUNAR,lunarError} from '../astronomy/ephemeris';import {cometCatalog,cometPosition,cometPeriod,camSamples,camRadius,localJPLAdapter} from '../astronomy/comets';
describe('Calendarios con referencias independientes',()=>{
 it('Smithsonian: 2012-12-21, GMT584283 = 13.0.0.0.0 · 4 Ajaw · 3 K’ank’in',()=>{const c=mayaCalendar(toJD({year:2012,month:12,day:21}));expect(c).toMatchObject({longCount:'13.0.0.0.0',tzolkinNumber:4,tzolkinName:'Ajaw',haabDay:3,haabMonth:'K’ank’in'});});
 it('Smithsonian/FAMSI: creación −3113-08-11 gregoriano = 4 Ajaw 8 Kumk’u',()=>{const c=mayaCalendar(toJD({year:-3113,month:8,day:11}));expect(c).toMatchObject({n:0,tzolkinNumber:4,tzolkinName:'Ajaw',haabDay:8,haabMonth:'Kumk’u'});});
 it('Rueda Calendárica repite cada 18980 días, incluido el pasado',()=>{for(const jd of [584000,2451545,2460000]){const a=mayaCalendar(jd),b=mayaCalendar(jd+18980);for(const k of ['tzolkinNumber','tzolkinName','haabDay','haabMonth','round'] as const)expect(a[k]).toBe(b[k]);}});
 it('HKO: 1984 Jiǎ-Zǐ, 2024 Dragón de Madera; 60 años repiten',()=>{expect(sexagenary(1984)).toMatchObject({index:1,animal:'Rata',element:'Madera'});expect(sexagenary(2024)).toMatchObject({animal:'Dragón',element:'Madera'});expect(sexagenary(2044)).toEqual(sexagenary(1984));});
 it('HKO almanaque2024: año nuevo 10 febrero, China UTC+8',()=>{const c=chineseCalendar(toJD({year:2024,month:2,day:10,hour:4}));expect(c).toMatchObject({year:2024,month:'1',day:1,animal:'Dragón',element:'Madera',leap:false});expect(chineseCalendar(toJD({year:2024,month:2,day:9,hour:4}))?.animal).toBe('Conejo');});
 it('Mes intercalar chino visible: 2023-03-22 (HKO calendario 2023)',()=>expect(chineseCalendar(toJD({year:2023,month:3,day:22,hour:4}))).toMatchObject({leap:true,day:1}));
 it('Proveedores no verificados no inventan datos',()=>{expect(tibetanProvider.calculate(defaults)).toMatchObject({month:null,day:null,parkha:null,mewa:null,omittedDay:null,duplicatedDay:null});expect(hanProvider.assign(defaults.jd)).toBeNull();});
 it('Nacimiento con cambio de fecha de zona natal',()=>expect(birthJD({...defaults,birth:'2024-04-09 01:30:00',birthZone:'Asia/Kolkata'})).toBeCloseTo(toJD({year:2024,month:4,day:8,hour:20}),8));
 it('Egipcio: época Nabonassar elegida, 12×30+5 y sin bisiestos',()=>{expect(egyptCalendar(EGYPT_EPOCH)).toMatchObject({year:1,month:'1',day:1,decan:1});expect(egyptCalendar(EGYPT_EPOCH+364)).toMatchObject({month:'Epagómenos',day:5,decan:null});expect(egyptCalendar(EGYPT_EPOCH+365)).toMatchObject({year:2,month:'1',day:1});});
 it('Cada código tiene seis líneas; transformaciones involutivas',()=>{for(let n=0;n<64;n++){expect(hexagramLines(n)).toHaveLength(6);expect(63-(63-n)).toBe(n);}});
});
describe('Astronomía y pañcāṅga',()=>{
 it('USNO: luna nueva 2024-04-08 18:21 UTC ±3 minutos',()=>{const start=toJD({year:2024,month:4,day:8,hour:12}),event=nextPhase(start,1)!;expect(event.phase).toBe(0);expect(Math.abs(event.jd-toJD({year:2024,month:4,day:8,hour:18,minute:21}))*1440).toBeLessThan(3);expect(longitudes(event.jd).illumination).toBeLessThan(.001);});
 it('USNO: luna llena 2024-04-23 23:49 UTC',()=>{const a=longitudes(toJD({year:2024,month:4,day:23,hour:23,minute:49}));expect(a.elongation).toBeCloseTo(180,1);expect(a.illumination).toBeGreaterThan(.999);});
 it('Referencia derivada USNO + sectores IMD: tithi30/Nāga antes y tithi1/Kiṃstughna después de conjunción',()=>{const before=toJD({year:2024,month:4,day:8,hour:17}),after=before+2/24;const a=longitudes(before),b=longitudes(after);const p=panchanga(a.sun,a.moon,before,ayanamsa(before,'lahiri')),q=panchanga(b.sun,b.moon,after,ayanamsa(after,'lahiri'));expect(p).toMatchObject({tithi:30,karana:'Nāga',nakshatra:'Revatī',yoga:'Vaidhṛti',vara:'Somavāra · lunes'});expect(q).toMatchObject({tithi:1,karana:'Kiṃstughna'});});
 it('Ayanāṃśa no cambia tithi; cambia nakṣatra y yoga',()=>{const tropical=panchanga(10,28,2451545,0),sidereal=panchanga(10,28,2451545,24);expect(tropical.tithi).toBe(sidereal.tithi);expect(tropical.nakshatra).not.toBe(sidereal.nakshatra);expect(tropical.yoga).not.toBe(sidereal.yoga);});
 it('Horizonte responde a localidad y declara día polar',()=>{const a=solarContext(defaults),b=solarContext({...defaults,latitude:28.6,longitude:77.2,zone:'Asia/Kolkata'});expect(a.sunrise).not.toBe(b.sunrise);expect(solarContext({...defaults,latitude:89,jd:toJD({year:2024,month:6,day:21})}).sunrise).toBeNull();});
 it('Precesión objetivo vuelve a la fase en 8.8826 años y error finito',()=>{expect(lunarMechanical(2451545+LUNAR.apsidalYears*365.25).apsis).toBeCloseTo(lunarMechanical(2451545).apsis,7);expect(Number.isFinite(lunarError(defaults.jd))).toBe(true);});
 for(const selected of moduleIds)it(`Contrato de módulo ${selected}: clasificación, método, fuentes y valores`,()=>{const r=calculateModule({...defaults,selected});expect(r.id).toBe(selected);expect(r.readings.length).toBeGreaterThan(2);expect(r.sourceIds.length).toBeGreaterThan(0);expect(r.method.length).toBeGreaterThan(20);expect(JSON.stringify(r)).not.toMatch(/NaN|undefined/);});
 it('Fechas extremas dan estado parcial astronómico, sin bloquear calendarios',()=>{expect(calculateModule({...defaults,jd:toJD({year:-4000,month:1,day:1})}).status).toBe('parcial');expect(calculateModule({...defaults,selected:'maya',jd:toJD({year:-4000,month:1,day:1})}).status).toBe('operativo');});
});
describe('Órbitas y levas de catálogo local JPL',()=>{
 for(const c of cometCatalog)it(`${c.name}: perihelio q, aphelio a(1+e) y cierre orbital`,()=>{const a=c.q/(1-c.e),p=cometPeriod(c);expect(cometPosition(c,c.perihelionJD).r).toBeCloseTo(c.q,8);expect(cometPosition(c,c.perihelionJD+p/2).r).toBeCloseTo(a*(1+c.e),7);expect(cometPosition(c,c.perihelionJD+p).r).toBeCloseTo(c.q,7);expect(camRadius(c,c.perihelionJD,camSamples(c))).toBeCloseTo(c.q,8);});
 it('Adaptador rechaza elementos hiperbólicos no soportados',()=>expect(()=>localJPLAdapter.parse(JSON.stringify([{...cometCatalog[0],e:1.2}]))).toThrow());
});
