import {resolveHexagram} from './yijing';
import type {Settings} from '../core/state';
import {J2000,localJD,formatJD,fromJD,mod,toJD,degrees} from '../core/time';
import {longitudes,lunarMechanical,lunarError,lunarSamples,solarContext,siriusContext,LUNAR,planets} from '../astronomy/ephemeris';
import {cometCatalog,cometPosition,cometPeriod,camRadius,camSamples} from '../astronomy/comets';
import {mayaCalendar,chineseCalendar,birthJD,egyptCalendar,hexagramLines,trigrams,stems,branches} from './calendars';
import {panchanga,ayanamsa,cosmicScales} from './panchanga';
import {tibetanProvider,type ModuleResult} from './contracts';
const row=(label:string,value:string|number)=>({label,value:String(value)});
const f=(n:number,d=3)=>n.toFixed(d);
const cache=new Map<string,unknown>();
function memo<T>(key:string,fn:()=>T):T{if(cache.has(key))return cache.get(key) as T;const value=fn();if(cache.size>48)cache.clear();cache.set(key,value);return value;}
export function calculateModule(s:Settings):ModuleResult{
 const local=localJD(s.jd,s.zone),year=fromJD(s.jd).year;
 const base={id:s.selected,classification:'ASTRONÓMICA' as const,status:'aproximado' as const,sourceIds:['ae'],uncertainty:'No se certifica precisión observacional. UTC ≈ UT1; sin segundos intercalares explícitos.'};
 if(s.selected==='maya'){const c=mayaCalendar(local,s.correlation);return {...base,classification:'HISTÓRICO-CALENDÁRICA',status:'operativo',hero:{label:'CUENTA LARGA',value:c.longCount,caption:`${c.tzolkinNumber} ${c.tzolkinName} · ${c.haabDay} ${c.haabMonth}`},readings:[row('Tzolk’in',`${c.tzolkinNumber} ${c.tzolkinName}`),row('Haab’',`${c.haabDay} ${c.haabMonth}`),row('Rueda Calendárica',`${c.round} / 18 980 días`),row('Posición Haab’',`${c.haabYear} / 52`),row('Cargador (0 Pop)',c.yearBearer),row('Correlación JDN',s.correlation),row('Cambio de día',`Medianoche · ${s.zone}`)],method:'Aritmética modular entera. Cuenta Larga 144000:7200:360:20:1; Tzolk’in 13×20 y Haab’ 18×20+5. Tren 52:73 convierte 260 a 365 días.',uncertainty:'GMT 584283 por defecto. El cargador del año se define aquí en 0 Pop; existen convenciones regionales distintas. Fechas previas a la época son extensión aritmética.',sourceIds:['maya','gmt']};}
 if(s.selected==='sino'){const c=chineseCalendar(s.jd),t=tibetanProvider.calculate(s);let birth='Fecha fuera del proveedor';try{const b=chineseCalendar(birthJD(s));if(b)birth=`${b.animal} de ${b.element} · ${b.stem} ${b.branch}`;}catch(e){birth=String(e);}
 return {...base,classification:'HISTÓRICO-CALENDÁRICA',status:'parcial',hero:{label:'CICLO SEXAGENARIO · CHINA',value:c?`${c.animal} de ${c.element}`:'Fuera de intervalo',caption:c?`${c.stem} · ${c.branch} · ${c.index} / 60`:'Proveedor chino disponible 1900–2100'},readings:[row('Mes lunar chino',c?`${c.month}${c.leap?' · intercalar':''}`:'No disponible'),row('Día lunar chino',c?.day??'No disponible'),row('Polaridad',c?.polarity??'—'),row('Zona del proveedor','Asia/Shanghai'),row('Matriz de nacimiento',birth),row('Localidad natal',s.birthPlace),row('Cálculos blancos','Proveedor tibetano pendiente'),row('Cálculos negros','Ciclo chino parcial'),row('Parkha · Mewa','Sin asignación verificada'),row('Días omitidos / duplicados','Tibetano: no calculado')],method:'Calendario chino Intl/ICU, zona civil china. Año Jiǎ-Zǐ 1984, 12 animales y cinco elementos por parejas de troncos. Datos natales convertidos desde la zona elegida. No hay recomendación favorable/desfavorable implementada.',uncertainty:t.note+' ICU depende de la versión del navegador. Las horas natales repetidas por DST usan la solución del iterador; no son una carta tibetana.',sourceIds:['hko','hko2024','tibet'],details:{tibetan:t,parkhaDemo:trigrams,mewaDemo:[1,2,3,4,5,6,7,8,9],birth}};}
 if(s.selected==='yijing'){const n=resolveHexagram(s),lines=hexagramLines(n),day=mod(Math.floor(local+.5)-2451551,60);
 return {...base,classification:'SIMBÓLICA-INTERPRETATIVA',status:s.yijingRule==='none'?'parcial':'demostrativo',hero:{label:'BIBLIOTECA DE TRANSFORMACIONES',value:`${trigrams[n&7]} / ${trigrams[n>>3]}`,caption:s.yijingRule==='none'?'Selección manual · ninguna asignación diaria':'Secuencia binaria propia · demostración v1'},readings:[row('Código binario (abajo → arriba)',lines.join('')),row('Tronco diario (convención)',stems[day%10]),row('Rama diaria (convención)',branches[day%12]),row('Regla Han','Sin proveedor verificado'),row('Regla activa',s.yijingRule),row('Inversión de las seis líneas',63-n)],method:'Representación estructural de seis líneas yin/yang. La demostración recorre 64 códigos binarios desde JDN 2451545, sin pretensión histórica. Tronco/rama diario con ancla demostrativa JDN 2451551 = Jiǎ-Zǐ, pendiente de validación histórica.',uncertainty:'No se atribuye un hexagrama diario al Yìjīng clásico ni a un sistema Han no implementado. Los índices binarios no son números King Wen.',sourceIds:['han','hko'],details:{lines,index:n}};}
 if(s.selected==='kalachakra'){const target=toJD({year:2424,month:1,day:1});return {...base,classification:'SIMBÓLICA-INTERPRETATIVA',status:'parcial',hero:{label:'HORIZONTE NARRATIVO',value:'2424 e. c.',caption:'Correspondencia tradicional propuesta'},readings:[row('Kalki XXV','Rudracakrin'),row('Marcador tradicional','Año 98 de su gobierno'),row('Año simulado',year),row('Distancia al año narrativo',`${2424-year} años civiles`),row('Cronología de otros Kalki','24 posiciones sin fechas asignadas'),row('Naturaleza del relato','Cronología religiosa')],method:'Corona independiente de las efemérides. Sigue la exposición de Alexander Berzin de la cronología Kālacakra. El 1 de enero sólo sitúa el marcador en la línea temporal; la fuente establece un año, no ese día.',uncertainty:'La gran guerra pertenece al relato doctrinal. No es una predicción científica confirmada. El linaje completo requiere edición crítica antes de completar nombres y fechas.',sourceIds:['kalachakra'],details:{targetJD:target,lineage:Array.from({length:25},(_,i)=>({ordinal:i+1,name:i===24?'Rudracakrin':'Nombre pendiente de edición crítica'}))}};}
 if(year< -2000||year>3000)return {...base,status:'parcial',hero:{label:'LÍMITE DEL MOTOR ASTRONÓMICO',value:'Fuera de intervalo',caption:'La cinemática y los calendarios siguen disponibles'},readings:[row('Año simulado',year)],method:'Se evita extrapolar efemérides fuera de −2000…3000.',uncertainty:'No hay lectura astronómica verificable en este intervalo.',sourceIds:['ae']};
 const a=longitudes(s.jd),sol=solarContext(s);
 if(s.selected==='lunar'){const mechanical=lunarMechanical(s.jd),chart=memo(`lunar:${Math.floor(s.jd)}`,()=>lunarSamples(Math.floor(s.jd)));return {...base,hero:{label:'ILUMINACIÓN LUNAR',value:`${f(a.illumination*100,1)} %`,caption:a.elongation<180?'Luna creciente':'Luna menguante'},readings:[row('Elongación Sol–Luna',`${f(a.elongation,2)}°`),row('Longitud numérica',`${f(a.moon)}°`),row('Salida pasador–ranura',`${f(mechanical.longitude)}°`),row('Error angular actual',`${f(lunarError(s.jd))}°`),row('Velocidad angular',`${f(mechanical.velocity)}° / día`),row('Precesión apsidal objetivo',`${LUNAR.apsidalYears} años`),row('Mes sinódico',`${LUNAR.synodic} d`),row('Mes sideral',`${LUNAR.sidereal} d`),row('Mes anomalístico',`${LUNAR.anomalistic} d`),row('Mes dracónico',`${LUNAR.draconic} d`),row('Altura solar local',`${f(sol.sunAltitude,1)}°`)],method:'Modelo numérico Astronomy Engine comparado con longitud media + corrección atan2 del pasador/ranura (e/r=.1098). Los centros k1/k2 difieren. Curva de desfase frente al modelo numérico durante los 365.25 días siguientes; muestreo de 7.61 días, no integral de error.',uncertainty:'La cinemática reproduce una primera anomalía aproximada y omite perturbaciones lunares. Periodos medios fijos; error mostrado, sin promesa de precisión histórica.',sourceIds:['ae','antikythera','moon'],chart:{label:'Desfase mecánico acumulado · 1 año',unit:'°',points:chart},details:{...a,...mechanical}};}
 if(s.selected==='vedic'){const ay=s.sidereal?ayanamsa(s.jd,s.ayanamsa):0;const dayJD=local-(s.dayBoundary==='sunrise'&&sol.sunrise!==null&&s.jd<sol.sunrise?1:0),p=panchanga(a.sun,a.moon,dayJD,ay);return {...base,hero:{label:'PAÑCĀṄGA · INSTANTE SIMULADO',value:`Tithi ${p.tithi}`,caption:p.fortnight},readings:[row('Vāra',p.vara),row('Nakṣatra',`${p.nakshatraIndex} · ${p.nakshatra}`),row('Yoga',`${p.yogaIndex} · ${p.yoga}`),row('Karaṇa',p.karana),row('λ Sol tropical',`${f(a.sun)}°`),row('λ Luna tropical',`${f(a.moon)}°`),row('Ayanāṃśa aplicada',`${f(ay,4)}° · ${s.sidereal?s.ayanamsa:'tropical'}`),row('Salida del Sol local',sol.sunrise?formatJD(localJD(sol.sunrise,s.zone)).slice(11):'Sin salida este día'),row('Cambio de vāra',s.dayBoundary==='sunrise'?'Salida del Sol':'Medianoche'),row('Altura solar',`${f(sol.sunAltitude,1)}°`)],method:'Tithi=floor((λL−λS) mod 360 /12)+1. Nakṣatra=floor(λL sidérea /(40/3))+1. Yoga=floor((λL+λS) sidéreas mod 360 /(40/3))+1. Karaṇa en semitithis. Miembros angulares calculados al instante, vāra según la frontera elegida.',uncertainty:`Ayanāṃśa lineal ilustrativa: Lahiri J2000 23.85675° o Fagan 24.7403°, deriva 50.29″/año. No réplica certificada de un pañcāṅga regional.${sol.sunrise===null?' Sin salida solar: se usa medianoche y se declara esta excepción.':''}`,sourceIds:['ae','panchanga','moon','cosmos'],details:{...p,planets:planets(s.jd),cosmicScales}};}
 const e=egyptCalendar(local),sirius=memo(`sir:${Math.floor(s.jd)}:${s.latitude}:${s.longitude}:${s.altitude}:${s.siriusAltitude}:${s.solarDepression}:${s.horizon}`,()=>siriusContext(s));return {...base,classification:'HISTÓRICO-CALENDÁRICA',hero:{label:'CALENDARIO CIVIL EGIPCIO',value:e.decan?`Decano ${e.decan} / 36`:'Días epagómenos',caption:`Año ${e.year} · mes ${e.month} · día ${e.day}`},readings:[row('Ciclo de diez días',e.decan?`${e.decadeDay} / 10`:'Fuera de las décadas'),row('Ciclo lunar ilustrativo',`${f(mod(s.jd-J2000,30),1)} / 30 d`),row('Orto helíaco candidato',sirius.heliacal?formatJD(localJD(sirius.heliacal,s.zone)).slice(0,10):'Sin cruce en un año'),row('Umbral de Sirio',`${s.siriusAltitude}° + horizonte ${s.horizon}°`),row('Sol al alba',`−${s.solarDepression}°`),row('Coordenadas',`${s.latitude}°, ${s.longitude}°`),row('Horizonte','Refracción estándar')],method:'Año civil de 365 días, época Nabonassar: −746-02-26 juliano. Decanos 36×10 más 5 epagómenos. La búsqueda de Sirio es astronómica aproximada y usa el primer cruce falso→verdadero del umbral a la altura solar seleccionada.',uncertainty:sirius.note,sourceIds:['egypt','dendera','ae'],details:{...e,...sirius}};
}
