import {useState,useEffect,useCallback,useRef} from 'react';
import {Play,Pause,ChevronLeft,ChevronRight,Search,BookOpen,Download,Camera,Sun,Moon,MapPin,HelpCircle,Upload,Volume2,VolumeX} from 'lucide-react';
import {useMachine,serialize} from '../core/state';
import Readings from './Readings';
import {SourcesDialog,TimeDialog,HelpDialog} from './Dialogs';
import {useExperience,download,toggleSound,useMechanicalSound} from './useExperience';
import {formatJD,stepTime,parseCivil,J2000,type Step} from '../core/time';
import {modules} from '../data/modules';
import SkyMap from './SkyMap';
import Wheel,{WheelInspector,useWheel} from '../wheel/wheel';
import {rings,groups,entries} from '../wheel/catalog';
import {isCivilTime,daysFromEpoch,MAX_DAYS,logarithmicPosition,durationLabel} from '../wheel/engine';
import DailySummaryPanel from './DailySummaryPanel';
export default function App(){
 const s=useMachine(),w=useWheel(),[surface,setSurface]=useState<'machine'|'sky'>('machine'),[query,setQuery]=useState(''),[step,setStep]=useState<Step>('día'),[dialog,setDialog]=useState<'sources'|'time'|'help'|null>(null),[timeError,setTimeError]=useState('');
 const close=useCallback(()=>setDialog(null),[]),fileInput=useRef<HTMLInputElement>(null),experience=useExperience();useMechanicalSound();const civil=isCivilTime(s.jd);
 useEffect(()=>{let last=performance.now(),carry=0,previousJD=NaN;const id=setInterval(()=>{const t=performance.now(),dt=Math.min((t-last)/1000,.25);last=t;const st=useMachine.getState();if(st.playing&&!document.hidden){if(st.jd!==previousJD)carry=0;carry+=dt*st.speed;const next=st.jd+carry;carry-=next-st.jd;previousJD=next;st.set({jd:Math.max(J2000-MAX_DAYS,Math.min(J2000+MAX_DAYS,next)),playing:Math.abs(next-J2000)<MAX_DAYS});}else{carry=0;previousJD=NaN;}},33);return()=>clearInterval(id);},[]);
 function advance(direction:number){const delta:Record<Step,number>={minuto:1/1440,hora:1/24,día:1,mes:30,año:365.25,siglo:36525,ciclo:18980};const jd=civil?stepTime(s.jd,step,direction,s.calendar):s.jd+Math.max(delta[step],Math.abs(s.jd)*Number.EPSILON)*direction;s.set({jd:Math.max(J2000-MAX_DAYS,Math.min(J2000+MAX_DAYS,jd)),playing:false});}
 return <div className={`app celestial-app ${s.night?'night':''} ${s.contrast?'contrast':''} ${s.hidden?'contemplation':''}`}>
 <header><div className="brand-icon">☉</div><div className="brand"><h1>MACHINA CÆLESTIS <span>UNIVERSALIS</span></h1><p>COMPUTADORA CELESTIAL</p></div><div className="header-right"><button onClick={()=>s.set({night:!s.night})} aria-label="Iluminación día o noche">{s.night?<Moon size={17}/>:<Sun size={17}/>}</button><button aria-label="Fuentes y supuestos" onClick={()=>setDialog('sources')}><BookOpen size={17}/><span>Fuentes</span></button><button aria-label="Tiempo y lugar" onClick={()=>setDialog('time')}><MapPin size={17}/></button><button aria-label="Ayuda" onClick={()=>setDialog('help')}><HelpCircle size={17}/></button></div></header>
 <span>EL TIEMPO EN UN EJE COMÚN</span>
 <div className="workspace"><aside className="sidebar"><div className="section-label">ATLAS DE LAS CORONAS <span>18</span></div><div className="search"><Search size={16}/><input aria-label="Buscar mecanismos" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar corona o lectura…"/><kbd>/</kbd></div><div className="ring-navigation">{groups.map(([group,title])=>{const matches=rings.filter(r=>r.group===group&&(r.name+r.culture).toLowerCase().includes(query.toLowerCase()));return matches.length?<section key={group}><h3>{title}</h3>{matches.map(r=><button key={r.id} className={w.ring===r.id?'selected':''} aria-pressed={w.ring===r.id} onClick={()=>{w.set({ring:r.id,entry:entries[r.id][0]});setSurface('machine');}}><span>{String(rings.indexOf(r)+1).padStart(2,'0')}</span>{r.name}</button>)}</section>:null;})}</div><details className="existing-modules" open><summary>Lecturas del observatorio</summary><div className="module-list">{modules.filter(x=>(x.title+x.latin).toLowerCase().includes(query.toLowerCase())).map(x=><button key={x.id} className={`module ${s.selected===x.id?'selected':''}`} onClick={()=>s.set({selected:x.id,piece:null})}><strong>{x.title}</strong></button>)}</div></details><div className="sidebar-foot"><div className="utility-actions"><button aria-label="Guardar estado JSON" title="Guardar estado JSON" onClick={()=>{download(serialize(s),'machina-estado.json');experience.setMessage('Estado exportado.');}}><Download size={17}/></button><button aria-label="Importar estado JSON" title="Importar estado JSON" onClick={()=>fileInput.current?.click()}><Upload size={17}/></button><input ref={fileInput} type="file" accept="application/json,.json" hidden aria-label="Archivo de estado" onChange={e=>{void experience.importFile(e.target.files?.[0]);e.target.value='';}}/><button aria-label="Capturar imagen" title="Capturar imagen" onClick={experience.capture}><Camera size={17}/></button><button aria-label="Sonido temporal" title="Sonido temporal" aria-pressed={s.sound} onClick={()=>void toggleSound().catch(()=>experience.setMessage('Sonido no disponible.'))}>{s.sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></div></div></aside>
 <main className={`scene-area surface-${surface}`}><div className="surface-tabs">{([['machine','Máquina'],['sky','Planisferio celeste']] as const).map(([id,label])=><button key={id} aria-pressed={surface===id} onClick={()=>setSurface(id)}>{label}</button>)}</div>{surface==='machine'&&<Wheel/>}{surface==='sky'&&(civil?<div className="visual-surface"><SkyMap/></div>:<div className="cosmic-notice">El horizonte astronómico admite fechas entre −4000 y 6000.<button onClick={s.now}>Sincronizar Hoy</button></div>)}{surface==='machine'&&<div className="cosmic-scale"><span>DURACIONES · ESCALA LOGARÍTMICA</span><div>{rings.filter(r=>['tonalpohualli','xiuhmolpilli','yugas','kalpa','mahakalpa'].includes(r.id)).map(r=><button key={r.id} style={{left:`${logarithmicPosition(r.period)*100}%`}} title={`${r.name}: ${durationLabel(r.period)}`} onClick={()=>w.set({ring:r.id,entry:entries[r.id][0]})}><i/>{r.id==='tonalpohualli'?'20 d':r.id==='xiuhmolpilli'?'Ataduras':r.name}</button>)}</div></div>}</main>
 <aside className="instrument-panel"><WheelInspector/><details className="astronomy-readings" open><summary>Observatorio · {modules.find(m=>m.id===s.selected)?.title}</summary>{civil?<Readings/>:<p className="cosmic-notice">Estás explorando una escala cosmológica. Las efemérides se reactivan al volver al intervalo −4000…6000.</p>}</details></aside></div>
 <DailySummaryPanel/>
 <footer className="timeline"><div className="time-heading"><span className="section-label">INSTANTE COMPARTIDO · UTC</span><button className="time-date" aria-label="Editar fecha UTC" onClick={()=>setDialog('time')}>{civil?formatJD(s.jd):`D = ${daysFromEpoch(s.jd).toExponential(8)} días`}</button><label className="date-picker-label">Fecha<input type="date" aria-label="Selector de fecha UTC" min="0001-01-01" max="6000-12-31" value={civil&&s.jd>=1721425.5?formatJD(s.jd).slice(0,10):''} onChange={e=>{try{if(!e.target.value)return;s.set({jd:parseCivil(e.target.value+' 12:00:00','gregorian'),playing:false});setTimeError('');}catch{setTimeError('Selecciona una fecha entre 0001 y 6000.');}}}/></label></div><div className="transport"><button aria-label="Paso anterior" onClick={()=>advance(-1)}><ChevronLeft size={20}/></button><button className="play" aria-label={s.playing?'Pausar':'Reproducir'} onClick={()=>s.set({playing:!s.playing})}>{s.playing?<Pause size={18}/>:<Play size={18}/>}</button><button aria-label="Paso siguiente" onClick={()=>advance(1)}><ChevronRight size={20}/></button><select aria-label="Unidad de paso" value={step} onChange={e=>setStep(e.target.value as Step)}>{['minuto','hora','día','mes','año','siglo','ciclo'].map(x=><option key={x}>{x}</option>)}</select></div><div className="time-rate"><label>Velocidad temporal<select aria-label="Velocidad temporal" value={s.speed} onChange={e=>s.set({speed:+e.target.value})}>{[-365.25,-365,-30,-1,1/86400,1,30,365,365.25,1e12].map(v=><option key={v} value={v}>{v===1/86400?'Tiempo real':Math.abs(v)===365.25?`${v<0?'−':''}1 año / segundo`:v===1e12?'10¹² días / segundo':`${v} días / segundo`}</option>)}</select></label></div><button className="now-button" onClick={s.now}>Sincronizar Hoy</button><div className="lunar-events"><button aria-label="Evento lunar anterior" disabled={!civil} onClick={()=>experience.event(-1)}>☾ ‹</button><button aria-label="Evento lunar siguiente" disabled={!civil} onClick={()=>experience.event(1)}>☾ ›</button></div></footer><div className="bottom-line"><span>{experience.offline?'DISPONIBLE SIN CONEXIÓN':'OBSERVATORIO LOCAL'} · {s.zone}</span><span>{civil?'FECHA CIVIL':'ESCALA COSMOLÓGICA'} · JD {s.jd.toPrecision(12)}</span></div>{timeError&&<p role="alert">{timeError}</p>}{dialog==='sources'&&<SourcesDialog close={close}/>} {dialog==='time'&&<TimeDialog close={close}/>} {dialog==='help'&&<HelpDialog close={close}/>} {experience.message&&<div role="status" className="toast">{experience.message}</div>} {s.hidden&&<button className="restore-ui" onClick={()=>s.set({hidden:false})}>Mostrar interfaz · Esc</button>}</div>;
}
