import {useEffect,useState} from 'react';import {useMachine,serialize,validateState} from '../core/state';import {toJD,parseCivil,J2000} from '../core/time';import {isCivilTime,MAX_DAYS} from '../wheel/engine';import {captureWheel} from '../wheel/capture';
export function download(data:string,name:string,type='application/json'){const url=type==='image/png'?data:URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();if(type!=='image/png')setTimeout(()=>URL.revokeObjectURL(url),500);}
export function useExperience(){const [message,setMessage]=useState(''),[offline,setOffline]=useState(false);
 useEffect(()=>{if(import.meta.env.PROD){import('virtual:pwa-register').then(({registerSW})=>registerSW({onOfflineReady:()=>setOffline(true)}));}const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches)useMachine.getState().set({playing:false});const change=()=>{if(media.matches)useMachine.getState().set({playing:false});};media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.defaultPrevented||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;const s=useMachine.getState();if(e.code==='Space'){e.preventDefault();s.set({playing:!s.playing});}if(e.key==='Escape')s.set({hidden:false});if(e.key==='/'){e.preventDefault();document.querySelector<HTMLInputElement>('[aria-label="Buscar mecanismos"]')?.focus();}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const jd=s.jd+(e.key==='ArrowLeft'?-1:1)*Math.max(1,Math.abs(s.jd)*Number.EPSILON);if(Math.abs(jd-J2000)<=MAX_DAYS)s.set({jd});}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
 useEffect(()=>{type Registry={registerTool:(tool:unknown,opts:unknown)=>void|Promise<void>};const context=(document as Document & {modelContext?:Registry}).modelContext;if(!context)return;const lifecycle=new AbortController();const tools=[{name:'read_observatory_state',description:'Lee el instante UTC y la configuración local del observatorio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>JSON.parse(serialize(useMachine.getState()))},{name:'configure_observatory_time',description:'Establece una fecha UTC gregoriana y pausa la máquina.',inputSchema:{type:'object',properties:{date:{type:'string'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const data=input as {date?:unknown};if(typeof data?.date!=='string')throw Error('Se requiere date como texto.');const jd=parseCivil(data.date,'gregorian');useMachine.getState().set({jd,playing:false});return {jd,paused:true};}}];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[]);
 const event=(direction:number)=>{setMessage('Buscando el siguiente cambio de fase lunar…');const worker=new Worker(new URL('../workers/calculation.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.error)setMessage(e.data.error);else if(e.data.result){useMachine.getState().set({jd:e.data.result.jd,playing:false});setMessage(`Evento lunar: elongación ${e.data.result.phase}°`);}else setMessage('No se encontró un evento dentro de 40 días.');worker.terminate();};worker.onerror=()=>{setMessage('No se pudo buscar el evento.');worker.terminate();};worker.postMessage({id:1,settings:JSON.parse(serialize(useMachine.getState())).state,eventDirection:direction});};
 const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>100000)throw Error('El archivo supera el límite de 100 kB.');const s=validateState(JSON.parse(await file.text()));useMachine.getState().set({...s,playing:false,hidden:false});setMessage('Estado importado y validado.');}catch(e){setMessage(`No se importó: ${(e as Error).message}`);}};
 const capture=async()=>{try{const wheel=document.querySelector<SVGSVGElement>('[data-testid="celestial-wheel"]');if(wheel){const png=await captureWheel(wheel);download(png,'machina-caelestis.png','image/png');}else{const canvas=document.querySelector('canvas');if(!canvas)throw Error('Selecciona la pestaña Máquina para capturar la rueda.');download(canvas.toDataURL('image/png'),'machina-caelestis.png','image/png');}setMessage('Captura de la escena guardada.');}catch(e){setMessage((e as Error).message);}};

 return {message,setMessage,offline,event,importFile,capture};
}
let audio:AudioContext|undefined;
export async function toggleSound(){const s=useMachine.getState();if(!s.sound){audio??=new AudioContext();await audio.resume();}s.set({sound:!s.sound});}
export function useMechanicalSound(){const sound=useMachine(s=>s.sound),playing=useMachine(s=>s.playing);useEffect(()=>{if(!sound||!playing)return;const timer=setInterval(()=>{if(document.hidden||!audio||audio.state!=='running')return;const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type='triangle';oscillator.frequency.value=420;gain.gain.setValueAtTime(.015,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.035);oscillator.connect(gain).connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.04);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};},240);return()=>clearInterval(timer);},[sound,playing]);}
