import {memo,useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {create} from 'zustand';
import {useMachine} from '../core/state';
import {J2000,mod} from '../core/time';
import {mayaCalendar} from '../modules/calendars';
import {hexagramInfo,resolveHexagram} from '../modules/yijing';
import {reflection,rings,entries,core,tropicalSolarSign,type Entry,type Ring} from './catalog';
import {daysFromEpoch,rotation,signedAngleDelta,dragDays,durationLabel,activeEntry,sectorStep} from './engine';

export const useWheel=create<{ring:string;entry:Entry;zoom:number;set:(patch:Partial<{ring:string;entry:Entry;zoom:number}>)=>void}>(set=>({ring:'tonalpohualli',entry:core,zoom:1,set}));
const point=(r:number,a:number)=>({x:r*Math.sin(a*Math.PI/180),y:-r*Math.cos(a*Math.PI/180)});
export function sector(inner:number,outer:number,start:number,end:number){const a=point(outer,start),b=point(outer,end),c=point(inner,end),d=point(inner,start),large=end-start>180?1:0;return `M${a.x},${a.y} A${outer},${outer} 0 ${large} 1 ${b.x},${b.y} L${c.x},${c.y} A${inner},${inner} 0 ${large} 0 ${d.x},${d.y} Z`;}
const asset=(file:string)=>import.meta.env.BASE_URL+file;
function Glyph({entry,large=false}:{entry:Entry;large?:boolean}){return entry.image?<img className={large?'glyph-large':'glyph-image'} src={asset(entry.image)} alt={entry.name}/>:<span className={`cultural-glyph ${entry.font||''}`}>{entry.glyph}</span>;}
export function EntryCard({entry,compact=false}:{entry:Entry;compact?:boolean}){const mahakalpa=entry.id.startsWith('mahakalpa-');return <><div className={`entry-visual${mahakalpa?' mahakalpa-visual':''}`}><Glyph entry={entry} large/></div><span className="entry-culture">{entry.culture}</span><h3 className={mahakalpa?'mahakalpa-title':undefined}>{entry.native}</h3><p className="entry-transliteration">{entry.transliteration}</p><h4>{entry.translation}</h4><p>{entry.description}</p>{!compact&&<><a href={entry.source} target="_blank" rel="noreferrer">Consultar procedencia ↗</a><small>{entry.author}<br/>{entry.license}</small></>}</>;}
function LiveRingReading({ring,days}:{ring:Ring;days:number}){const state=useMachine(),correlation=state.correlation;const rows=entries[ring.id],current=activeEntry(days,ring,rows);
 if(ring.id==='iching'){const code=resolveHexagram(state),h=hexagramInfo(code);return <div className="live-ring-reading" aria-label="Pronóstico del I Ching"><span>{state.yijingRule==='none'?'HEXAGRAMA MANUAL':'HEXAGRAMA DEL INSTANTE · SECUENCIA J2000'}</span><strong>{current.glyph} {current.native} · {current.name}</strong><p>{reflection(current.code??code)}</p></div>;}
 if(['tzolkin','tzolkin-number','haab'].includes(ring.id)&&Math.abs(days)<1e7){const m=mayaCalendar(days+J2000,correlation);return <div className="live-ring-reading"><span>FECHA MAYA · CORRELACIÓN {correlation}</span><strong>{m.tzolkinNumber} {m.tzolkinName} · {m.haabDay} {m.haabMonth}</strong><p>Glifo bajo el índice: {current.name}. Cuenta Larga {m.longCount}. La fase del disco se mide desde J2000.</p></div>;}
 if(ring.id==='zodiac'){return <div className="live-ring-reading"><span>BAJO EL ÍNDICE · FASE DESDE J2000</span><strong>{tropicalSolarSign(days)}</strong></div>;}
 return <div className="live-ring-reading"><span>BAJO EL ÍNDICE · FASE DESDE J2000</span><strong>{current.name}</strong></div>;
}
export function WheelInspector(){const w=useWheel(),r=rings.find(r=>r.id===w.ring)!,days=useMachine(s=>s.d??daysFromEpoch(s.jd));useEffect(()=>{w.set({entry:activeEntry(days,r,entries[r.id])});},[days,r.id]);return <section className="wheel-inspector" aria-label="Inspector cultural"><div className="section-label">LECTURA DE LA CORONA</div><label className="field">Disco activo<select aria-label="Disco activo" value={w.ring} onChange={e=>w.set({ring:e.target.value})}>{rings.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><div className="phase-reading"><span>{durationLabel(r.period)} / vuelta</span><strong data-testid="ring-angle">{rotation(days+(r.phaseOffset||0),r.period).toPrecision(7)}°</strong></div><LiveRingReading ring={r} days={days}/><label className="field">Glifo o división<select aria-label="Glifo o división" value={w.entry.id===core.id?core.id:w.entry.id} onChange={e=>w.set({entry:e.target.value===core.id?core:entries[w.ring].find(x=>x.id===e.target.value)!})}><option value={core.id}>Tonatiuh · centro</option>{entries[w.ring].map(e=><option key={e.id} value={e.id}>{e.name} · {e.translation}</option>)}</select></label><article className="entry-detail"><EntryCard entry={w.entry}/>{r.id==='mewa'&&<div className="mewa-square" aria-label="Cuadrado mágico Mewa, suma 15">{[4,9,2,3,5,7,8,1,6].map(n=><span key={n}>{n}</span>)}</div>}</article></section>;}
const RingArt=memo(function RingArt({ring:r,days,onInspect}:{ring:Ring;days:number;onInspect:(entry:Entry,ring:Ring,x?:number,y?:number)=>void}){
 const rows=entries[r.id],sum=rows.reduce((n,e)=>n+(e.weight||1),0);let offset=0;
 return <>{r.image&&<image href={asset(r.image)} x={-r.outer} y={-r.outer} width={r.outer*2} height={r.outer*2} clipPath={`url(#clip-${r.id})`} opacity=".4" filter="url(#gold-ink)"/>}{rows.map((entry,i)=>{const span=(entry.weight||1)/sum*360,angle=-offset-span/2;offset+=span;const middle=(r.inner+r.outer)/2,p=point(middle,angle),height=r.outer-r.inner-4,width=Math.min(height,2*Math.PI*middle*span/360*.8),tiny=width<12;return <g className="wheel-glyph" key={entry.id} data-entry={entry.id} onPointerEnter={e=>onInspect(entry,r,e.clientX,e.clientY)} onFocus={()=>onInspect(entry,r)} onClick={()=>useWheel.getState().set({ring:r.id,entry})}>
 <path d={sector(r.inner,r.outer,angle-span/2,angle+span/2)} fill={i%2?'#a9813810':'#fff5cc33'} stroke="#86622f" strokeWidth=".45"/>
 <g transform={`translate(${p.x} ${p.y}) rotate(${angle})`} pointerEvents="none">{r.id==='xiuhmolpilli'?<circle r="2.3" fill="none" stroke="#754a16" strokeWidth="1"/>:entry.image&&r.id!=='dendera'?<image href={asset(entry.image)} x={-width/2} y={-height/2} width={width} height={height} preserveAspectRatio="xMidYMid meet" filter="url(#gold-ink)"/>:<text className={entry.font||''} textAnchor="middle" dominantBaseline="central" fill="#513b1b" fontSize={r.id==='iching'?18:r.id==='dendera'?16:tiny?7:Math.min(height*.69,19)}>{r.id==='xiuhpohualli'?String(i+1):r.id==='dendera'?(i===36?'+5':entry.glyph):entry.glyph}</text>}</g><title>{entry.name} · {entry.translation}</title></g>;})}<circle r={r.inner} fill="none" stroke="#8a6629" strokeWidth="1"/><circle r={r.outer} fill="none" stroke="#9d793c" strokeWidth="1.2"/></>;
});
const RotatingRing=memo(function RotatingRing({ring,days,selected,onInspect,onStart}:{ring:Ring;days:number;selected:boolean;onInspect:(entry:Entry,ring:Ring,x?:number,y?:number)=>void;onStart:(event:ReactPointerEvent<SVGGElement>,ring:Ring)=>void}){
const angle=rotation(days,ring,ring.phaseOffset||0,entries[ring.id].map(e=>e.weight||1));
return <g className={`wheel-ring ${selected?'ring-selected':''}`} data-ring={ring.id} data-angle={angle} transform={`rotate(${angle})`} role="button" tabIndex={0} aria-label={`Girar ${ring.name}`} aria-pressed={selected} onPointerDown={e=>onStart(e,ring)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();useWheel.getState().set({ring:ring.id,entry:entries[ring.id][0]});if(e.key.startsWith('Arrow'))useMachine.getState().set({jd:J2000+sectorStep(days,ring.period,entries[ring.id].map(e=>e.weight||1),e.key==='ArrowLeft'?-1:1,ring.phaseOffset||0),playing:false,...(ring.id==='iching'?{yijingRule:'binary-demo-v1' as const}:{})});}}}><RingArt ring={ring} days={days} onInspect={onInspect}/></g>;
});
export default function Wheel(){const days=useMachine(s=>s.d??daysFromEpoch(s.jd)),w=useWheel(),svg=useRef<SVGSVGElement>(null),drag=useRef<{pointer:number;angle:number;ring:Ring;origin:number;delta:number}|null>(null),[tooltip,setTooltip]=useState<{entry:Entry;x:number;y:number}|null>(null);
 const inspect=useRef((entry:Entry,ring:Ring,x?:number,y?:number)=>{if(drag.current)return;if(x!==undefined&&y!==undefined)setTooltip({entry,x,y});}).current;
 function angleAt(x:number,y:number){const matrix=svg.current?.getScreenCTM();if(!matrix)return 0;const p=new DOMPoint(x,y).matrixTransform(matrix.inverse());return Math.atan2(p.y,p.x)*180/Math.PI;}
 function start(event:ReactPointerEvent<SVGGElement>,ring:Ring){if(event.button!==0)return;event.preventDefault();setTooltip(null);svg.current?.setPointerCapture(event.pointerId);drag.current={pointer:event.pointerId,angle:angleAt(event.clientX,event.clientY),ring,origin:useMachine.getState().d??daysFromEpoch(useMachine.getState().jd),delta:0};const id=(event.target as Element).closest('[data-entry]')?.getAttribute('data-entry');useWheel.getState().set({ring:ring.id,entry:entries[ring.id].find(e=>e.id===id)||entries[ring.id][0]});useMachine.getState().set({playing:false,...(ring.id==='iching'?{yijingRule:'binary-demo-v1' as const}:{})});}
 function move(event:ReactPointerEvent<SVGSVGElement>){const d=drag.current;if(!d||d.pointer!==event.pointerId)return;const angle=angleAt(event.clientX,event.clientY),delta=signedAngleDelta(d.angle,angle);d.angle=angle;d.delta+=delta;const s=useMachine.getState(),nextDays=dragDays(d.origin,d.delta,d.ring.period);s.set({d:nextDays,jd:J2000+nextDays});}
 function end(event:ReactPointerEvent<SVGSVGElement>){if(drag.current?.pointer!==event.pointerId)return;drag.current=null;if(svg.current?.hasPointerCapture(event.pointerId))svg.current.releasePointerCapture(event.pointerId);}
 return <div className="wheel-stage" onPointerLeave={()=>setTooltip(null)}><div className="wheel-heading"><div><span className="eyebrow">MACHINA CAELESTIS UNIVERSALIS</span><h2>Computadora Celestial</h2></div><span className="wheel-edition">XVIII CORONAS<br/>UN SOLO INSTANTE</span></div><div className="wheel-viewport"><svg ref={svg} data-testid="celestial-wheel" xmlns="http://www.w3.org/2000/svg" viewBox={`${-590/w.zoom} ${-590/w.zoom} ${1180/w.zoom} ${1180/w.zoom}`} aria-label="Rueda celestial concéntrica interactiva" onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={()=>{drag.current=null;}} onWheel={e=>{if(e.ctrlKey)return;w.set({zoom:Math.max(1,Math.min(4,w.zoom+(e.deltaY<0?.1:-.1)))});setTooltip(null);}}>
 <defs><radialGradient id="wheel-metal"><stop offset="0" stopColor="#fff8d6"/><stop offset=".58" stopColor="#ecdbac"/><stop offset=".83" stopColor="#fbefd0"/><stop offset="1" stopColor="#cfb477"/></radialGradient><filter id="gold-ink" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values=".24 .48 .1 0 .17 .2 .4 .08 0 .12 .1 .23 .04 0 .035 0 0 0 1 0"/></filter><clipPath id="tonatiuh-clip"><circle r="80"/></clipPath>{rings.filter(r=>r.image).map(r=><clipPath key={r.id} id={`clip-${r.id}`}><path d={`M${r.outer},0a${r.outer},${r.outer} 0 1,0 ${-r.outer*2},0a${r.outer},${r.outer} 0 1,0 ${r.outer*2},0 M${r.inner},0a${r.inner},${r.inner} 0 1,1 ${-r.inner*2},0a${r.inner},${r.inner} 0 1,1 ${r.inner*2},0`} clipRule="evenodd"/></clipPath>)}</defs>
 <g className="wheel-grid" pointerEvents="none" stroke="#c3a765" fill="none">{[560,574].map(r=><circle key={r} r={r} strokeWidth=".7"/>)}{Array.from({length:72},(_,i)=>{const a=point(554,i*5),b=point(i%3?561:568,i*5);return <path key={i} d={`M${a.x} ${a.y}L${b.x} ${b.y}`} strokeWidth={i%3?.6:1.2}/>;})}</g>
 <circle r="549" fill="url(#wheel-metal)" stroke="#89622b" strokeWidth="3"/>
 {rings.map(r=><RotatingRing key={r.id} ring={r} days={days} selected={w.ring===r.id} onInspect={inspect} onStart={start}/>)}
 <g className="wheel-core" role="button" tabIndex={0} aria-label="Tonatiuh · Piedra del Sol" onClick={()=>w.set({entry:core})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();w.set({entry:core});}}} onPointerEnter={e=>setTooltip({entry:core,x:e.clientX,y:e.clientY})}><circle r="85" fill="#ead19b" stroke="#895e22" strokeWidth="2"/><image href={asset('art/tonatiuh.jpg')} x="-82" y="-82" width="164" height="164" clipPath="url(#tonatiuh-clip)" filter="url(#gold-ink)"/><title>Tonatiuh · Piedra del Sol</title></g>
 <path d="M-6 -575L0 -552L6 -575Z" fill="#285f67" stroke="#f5e7c0" pointerEvents="none"/>
 </svg></div><div className="wheel-tools"><button aria-label="Alejar rueda" disabled={w.zoom<=1} onClick={()=>w.set({zoom:Math.max(1,w.zoom-.25)})}>−</button><button aria-label="Encuadrar rueda" onClick={()=>w.set({zoom:1})}>{Math.round(w.zoom*100)}%</button><button aria-label="Acercar rueda" disabled={w.zoom>=4} onClick={()=>w.set({zoom:Math.min(4,w.zoom+.25)})}>+</button><button onClick={()=>useMachine.getState().set({hidden:true})}>Contemplar</button></div><div className="wheel-caption"><span>Arrastra una corona para recorrer el tiempo</span><span>J2000 · D <b data-testid="master-days">{Math.abs(days)>1e7?days.toExponential(7):days.toFixed(5)}</b></span></div>{tooltip&&<div className="wheel-tooltip" role="tooltip" style={{left:Math.min(Math.max(8,tooltip.x+18),window.innerWidth-308),top:Math.max(8,Math.min(tooltip.y+18,window.innerHeight-470))}}><EntryCard entry={tooltip.entry} compact/><small>Pulsa el glifo para fijar su lectura.</small></div>}</div>;
}
