import {degrees,rad,toJD,mod} from '../core/time';
export interface CometElements{id:string;name:string;epochJD:number;q:number;e:number;i:number;node:number;argPeri:number;perihelionJD:number;source:string;reference:string}
export const cometCatalog:CometElements[]=[{id:'halley',name:'1P/Halley',epochJD:2449400.5,q:.58597811,e:.96714291,i:162.26269,node:58.42008,argPeri:111.33249,perihelionJD:toJD({year:1986,month:2,day:5})+.89532,source:'https://ssd.jpl.nasa.gov/sb/elem_tables.html',reference:'JPL J863/77 · tabla de ejemplo, elementos osculantes'}, {id:'encke',name:'2P/Encke',epochJD:2455460.5,q:.33586872,e:.84833156,i:11.78308,node:334.56582,argPeri:186.54970,perihelionJD:toJD({year:2010,month:8,day:6})+.50196,source:'https://ssd.jpl.nasa.gov/sb/elem_tables.html',reference:'JPL K105/1 · tabla de ejemplo'}];
export const cometPeriod=(c:CometElements)=>2*Math.PI/.01720209895*Math.pow(c.q/(1-c.e),1.5);
export function cometPosition(c:CometElements,jd:number){const a=c.q/(1-c.e),M=rad(degrees(360*(jd-c.perihelionJD)/cometPeriod(c)));let E=M<Math.PI?M+c.e/2:M-c.e/2;for(let i=0;i<30;i++){const delta=(E-c.e*Math.sin(E)-M)/(1-c.e*Math.cos(E));E-=delta;if(Math.abs(delta)<1e-12)break;}
 const x=a*(Math.cos(E)-c.e),y=a*Math.sqrt(1-c.e*c.e)*Math.sin(E),nu=Math.atan2(y,x),r=Math.hypot(x,y),u=nu+rad(c.argPeri),node=rad(c.node),inc=rad(c.i);
 return {r,nu:degrees(nu*180/Math.PI),x:r*(Math.cos(node)*Math.cos(u)-Math.sin(node)*Math.sin(u)*Math.cos(inc)),y:r*(Math.sin(node)*Math.cos(u)+Math.cos(node)*Math.sin(u)*Math.cos(inc)),z:r*Math.sin(u)*Math.sin(inc)};
}
export function camSamples(c:CometElements,count=128){return Array.from({length:count+1},(_,i)=>({x:i/count,y:cometPosition(c,c.perihelionJD+i/count*cometPeriod(c)).r}));}
export function camRadius(c:CometElements,jd:number,samples=camSamples(c)){const f=mod((jd-c.perihelionJD)/cometPeriod(c),1)*(samples.length-1),i=Math.floor(f);return samples[i].y+(samples[i+1].y-samples[i].y)*(f-i);}
export interface JPLAdapter {name:string;parse(text:string):CometElements[];source:string}
export const localJPLAdapter:JPLAdapter={name:'jpl-elements-json-v1',source:'https://ssd-api.jpl.nasa.gov/doc/sbdb.html',parse(text){const rows=JSON.parse(text);if(!Array.isArray(rows))throw Error('Se requiere un catálogo JSON normalizado.');return rows.map((r:CometElements)=>{if(!['q','e','i','node','argPeri','perihelionJD','epochJD'].every(k=>Number.isFinite(r[k as keyof CometElements]))||r.q<=0||r.e<0||r.e>=1||typeof r.name!=='string'||typeof r.source!=='string')throw Error('Elementos elípticos inválidos.');return r;});}};
