import {test,expect} from '@playwright/test';
test('Arrastre, teclado, numerales mayas, pronóstico y regreso desde un eón',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');
 await page.getByRole('button',{name:'Editar fecha UTC'}).click();await page.getByRole('textbox',{name:'Fecha UTC'}).fill('2000-01-01 12:00:00');await page.getByRole('button',{name:'Aplicar tiempo y lugar'}).click();
 const ring=page.locator('[data-ring="tonalpohualli"]');await ring.focus();await page.keyboard.press('ArrowRight');await expect(page.getByTestId('master-days')).toHaveText('1.00000');await page.keyboard.press('ArrowLeft');await expect(page.getByTestId('master-days')).toHaveText('0.00000');
 const box=(await page.getByTestId('celestial-wheel').boundingBox())!,scale=Math.min(box.width,box.height)/1180,cx=box.x+box.width/2,cy=box.y+box.height/2,r=106*scale;
 await page.mouse.move(cx,cy-r);await page.mouse.down();for(let i=1;i<=12;i++){const a=i/12*Math.PI/2;await page.mouse.move(cx+r*Math.sin(a),cy-r*Math.cos(a));}await page.mouse.up();await expect.poll(async()=>Number(await page.getByTestId('master-days').textContent())).toBeCloseTo(5,1);await expect(page.locator('[data-ring="haab"]')).not.toHaveAttribute('data-angle','0');
 await page.getByLabel('Disco activo').selectOption('iching');const before=await page.getByLabel('Pronóstico del I Ching').textContent();await page.getByRole('button',{name:'Paso siguiente',exact:true}).click();await expect(page.getByLabel('Pronóstico del I Ching')).not.toHaveText(before!);
 await page.locator('[data-ring="mahakalpa"]').focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('button',{name:'Editar fecha UTC'})).toContainText('D =');await expect(page.locator('.instrument-panel')).toContainText('escala cosmológica');await page.getByRole('button',{name:'Sincronizar Hoy',exact:true}).click();await expect(page.getByRole('button',{name:'Editar fecha UTC'})).not.toContainText('D =');expect(errors).toEqual([]);
});
test('Glifos, ampliación, captura PNG y assets completos',async({page})=>{const failures:string[]=[];page.on('response',r=>{if(r.status()>=400)failures.push(r.url());});await page.goto('./');await page.getByLabel('Disco activo').selectOption('tonalpohualli');await page.getByLabel('Glifo o división').selectOption('nahua-day-16');await expect(page.locator('.entry-detail h3')).toHaveText('Ōllin');await page.getByRole('button',{name:'Acercar rueda'}).click();await expect(page.getByRole('button',{name:'Encuadrar rueda'})).toHaveText('125%');await page.getByRole('button',{name:'Encuadrar rueda'}).click();await expect(page.getByRole('button',{name:'Encuadrar rueda'})).toHaveText('100%');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Capturar imagen'}).click();const png=await download;expect(png.suggestedFilename()).toBe('machina-caelestis.png');await png.saveAs('docs/rueda-celestial.png');expect(failures).toEqual([]);});
test('Selector civil y reproducción reversible',async({page})=>{await page.goto('./');await page.getByLabel('Selector de fecha UTC').fill('2012-12-21');await expect(page.getByRole('button',{name:'Editar fecha UTC'})).toContainText('2012-12-21 12:00:00');await page.getByLabel('Disco activo').selectOption('tzolkin');await expect(page.locator('.live-ring-reading')).toContainText('4 Ajaw');await page.getByLabel('Velocidad temporal').selectOption('-1');await page.getByRole('button',{name:'Reproducir',exact:true}).click();await expect.poll(async()=>Number(await page.getByTestId('master-days').textContent())).toBeLessThan(4738);await page.getByRole('button',{name:'Pausar',exact:true}).click();await expect(page.getByRole('button',{name:'Reproducir',exact:true})).toBeVisible();});
test('Resumen pancultural se actualiza, colapsa y enfoca una corona',async({page})=>{await page.goto('./');const summary=page.getByRole('region',{name:'Efemérides panculturales y resumen del día'});await expect(summary).toContainText('Cuenta Larga');await expect(summary).toContainText('Día Juliano');await summary.getByRole('button',{name:/Maya · enfocar corona/}).click();await expect(page.getByLabel('Disco activo')).toHaveValue('tzolkin');await summary.getByRole('button',{name:'Colapsar resumen del día'}).click();await expect(summary.getByRole('button',{name:'Expandir resumen del día'})).toBeVisible();await expect(summary).not.toContainText('Cuenta Larga');await summary.getByRole('button',{name:'Expandir resumen del día'}).click();await expect(summary).toContainText('Cuenta Larga');await page.getByLabel('Selector de fecha UTC').fill('2012-12-21');await expect(summary).toContainText('13.0.0.0.0');});
