import * as THREE from 'three';
import {nahuaDays,mayaDays,mayaMonths,culturalEntries,type DialEntry} from '../data/dial-cultures';
const size=2048,c=size/2;
const fontNames:Record<string,string>={egypt:'Egypt',runic:'Runic',cuneiform:'Cuneiform',devanagari:'Devanagari',tibetan:'Tibetan',mayan:'Mayan'};
const images=new Map<string,HTMLImageElement>();
function canvas(){const node=document.createElement('canvas');node.width=node.height=size;return {node,ctx:node.getContext('2d')!};}
function texture(node:HTMLCanvasElement){const t=new THREE.CanvasTexture(node);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
function disc(ctx:CanvasRenderingContext2D,r:number,fill:string,line='#a7752f'){ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=line;ctx.lineWidth=5;ctx.stroke();}
function glyph(ctx:CanvasRenderingContext2D,e:DialEntry,x:number,y:number,w:number){const image=e.image&&images.get(e.image);if(image){const scale=w/Math.max(image.naturalWidth,image.naturalHeight);ctx.drawImage(image,x-image.naturalWidth*scale/2,y-image.naturalHeight*scale/2,image.naturalWidth*scale,image.naturalHeight*scale);}else {ctx.font=`${w*.77}px ${fontNames[e.font||'']||'serif'}`;ctx.fillStyle='#624015';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(e.glyph||'',x,y,w*1.6);}}
export function ringTexture(entries:DialEntry[],inner:number,outer:number,colors:string[]){const {node,ctx}=canvas(),r=1000,ri=r*inner/outer,mid=(r+ri)/2,w=(r-ri)*.63;disc(ctx,r,'#cb9a45');disc(ctx,r-13,'#f9e8b7');disc(ctx,ri,'#a27330');for(let i=0;i<entries.length;i++){const a=i/entries.length*Math.PI*2;ctx.save();ctx.translate(c,c);ctx.rotate(a);ctx.fillStyle=colors[i%colors.length];ctx.beginPath();ctx.arc(0,0,r-17,-Math.PI/2-Math.PI/entries.length+.015,-Math.PI/2+Math.PI/entries.length-.015);ctx.arc(0,0,ri+12,-Math.PI/2+Math.PI/entries.length-.015,-Math.PI/2-Math.PI/entries.length+.015,true);ctx.closePath();ctx.fill();ctx.restore();const x=c+Math.sin(a)*mid,y=c-Math.cos(a)*mid;glyph(ctx,entries[i],x,y,w);ctx.save();ctx.translate(c+Math.sin(a)*(ri+22),c-Math.cos(a)*(ri+22));ctx.rotate(a);ctx.font='19px Georgia';ctx.textAlign='center';ctx.fillStyle='#4d3019';ctx.fillText(entries[i].name,0,0);ctx.restore();}ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(c,c,ri-2,0,Math.PI*2);ctx.fill();return texture(node);}
function supportTexture(culture:string){const {node,ctx}=canvas();disc(ctx,1000,'#b28039');disc(ctx,950,'#eed7a0');disc(ctx,700,'#174c50');const entries=culturalEntries.filter(e=>e.culture===culture);for(let i=0;i<Math.max(entries.length,8);i++){const a=i/Math.max(entries.length,8)*Math.PI*2,e=entries[i%entries.length];if(e)glyph(ctx,e,c+Math.sin(a)*825,c-Math.cos(a)*825,165);}ctx.strokeStyle='#b89750';ctx.lineWidth=8;for(let i=0;i<16;i++){const a=i*Math.PI/8;ctx.save();ctx.translate(c,c);ctx.rotate(a);ctx.beginPath();ctx.moveTo(0,-675);ctx.bezierCurveTo(160,-550,160,-440,0,-330);ctx.bezierCurveTo(-160,-440,-160,-550,0,-675);ctx.stroke();ctx.restore();}return texture(node);}
let promise:Promise<{nahua:THREE.Texture;maya:THREE.Texture;haab:THREE.Texture;supports:THREE.Texture[]}>|undefined;
export function culturalTextures(){return promise??= (async()=>{await Promise.all([...Object.values(fontNames).map(name=>document.fonts.load(`40px ${name}`)),...[...nahuaDays,...mayaDays,...mayaMonths].map(e=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>{images.set(e.image!,img);resolve();};img.onerror=()=>reject(Error('No se pudo cargar '+e.image));img.src=import.meta.env.BASE_URL+e.image;}))]);return {nahua:ringTexture(nahuaDays,1.38,2.12,['#e9b66d','#bad2bf','#d89d76','#f1dfaa']),maya:ringTexture(mayaDays,2.16,2.83,['#ecd8a2','#c8d7be']),haab:ringTexture(mayaMonths,2.87,3.53,['#f1dfaf','#dfc393']),supports:['Grecia','Egipto','China','China','India','Egipto','Tíbet','Mesopotamia'].map(supportTexture)};})();}
