import {Suspense,useEffect,useMemo,useRef,Component,type ReactNode} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Stars,GizmoHelper,GizmoViewport,Line} from '@react-three/drei';
import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {useShallow} from 'zustand/react/shallow';import ModuleInstrument from './ModuleInstrument';
import {useMachine} from '../core/state';
import {J2000} from '../core/time';
import {modules} from '../data/modules';
import {gears,ratios,centers} from '../mechanics/machine';
import {angleAt,thermalScale,pinSlot,type Gear} from '../mechanics/solver';
const cache=new Map<string,THREE.BufferGeometry>();
function gearGeometry(teeth:number,pitch:number){
 const key=`${teeth}:${pitch}`;if(cache.has(key))return cache.get(key)!;
 const r=teeth*pitch/2,shape=new THREE.Shape();
 for(let i=0;i<teeth*4;i++){const a=i/(teeth*4)*Math.PI*2,rr=r+(i%4<2?pitch*.65:-pitch*.65);const x=rr*Math.cos(a),y=rr*Math.sin(a);if(i===0)shape.moveTo(x,y);else shape.lineTo(x,y);}shape.closePath();
 const hole=new THREE.Path();hole.absarc(0,0,r*.7,0,Math.PI*2,true);shape.holes.push(hole);
 const ring=new THREE.ExtrudeGeometry(shape,{depth:.095,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.008,bevelThickness:.007});ring.translate(0,0,-.0475);
 const components:THREE.BufferGeometry[]=[ring];
 for(let i=0;i<3;i++){const spoke=new THREE.BoxGeometry(r*1.7,pitch*2,.095);spoke.rotateZ(i*Math.PI/3);components.push(spoke.toNonIndexed());}
 const hub=new THREE.CylinderGeometry(r*.22,r*.22,.18,20);hub.rotateX(Math.PI/2);components.push(hub.toNonIndexed());
 const geo=mergeGeometries(components.map(g=>{g.deleteAttribute('uv');return g;}));components.forEach(g=>g.dispose());cache.set(key,geo);return geo;
}
function dialTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=2048;const ctx=canvas.getContext('2d')!,c=1024;ctx.fillStyle='#10242e';ctx.fillRect(0,0,2048,2048);
 for(let ring=0;ring<7;ring++){ctx.beginPath();ctx.arc(c,c,970-ring*20,0,Math.PI*2);ctx.strokeStyle=ring%2?'#587078':'#a68b58';ctx.lineWidth=ring%2?1:3;ctx.stroke();}
 for(let i=0;i<360;i++){const a=i*Math.PI/180;ctx.beginPath();ctx.moveTo(c+Math.sin(a)*970,c-Math.cos(a)*970);const r=i%10===0?915:i%5===0?929:944;ctx.lineTo(c+Math.sin(a)*r,c-Math.cos(a)*r);ctx.strokeStyle=i%10===0?'#d9c08a':'#6a7979';ctx.lineWidth=i%10===0?3:1;ctx.stroke();}
 ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#d0bc8c';ctx.font='25px Georgia';const names=['ARIES','TAURUS','GEMINI','CANCER','LEO','VIRGO','LIBRA','SCORPIO','SAGITTARIUS','CAPRICORNUS','AQUARIUS','PISCES'];for(let i=0;i<12;i++){ctx.save();ctx.translate(c,c);ctx.rotate(i*Math.PI/6);ctx.fillText(names[i],0,-862);ctx.restore();}
 ctx.strokeStyle='#47606a';ctx.lineWidth=2;for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(c+Math.cos(a)*250,c+Math.sin(a)*250);ctx.lineTo(c+Math.cos(a)*790,c+Math.sin(a)*790);ctx.stroke();}
 const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t;}
function GearMesh({gear,highlight}:{gear:Gear;highlight:boolean}){
 const ref=useRef<THREE.Group>(null);const {set,piece,backlash,temperature,physics,transparent}=useMachine(useShallow(s=>({set:s.set,piece:s.piece,backlash:s.backlash,temperature:s.temperature,physics:s.physics,transparent:s.transparent})));
 useFrame(()=>{if(ref.current)ref.current.rotation.z=angleAt(useMachine.getState().jd,gear.inputPeriod,ratios.get(gear.id)!,physics?backlash:0)+(gear.connection==='external'?Math.PI/gear.teeth:0);});
 const geo=useMemo(()=>gearGeometry(gear.teeth,gear.pitch),[gear.teeth,gear.pitch]);
 return <group position={gear.position} scale={physics?thermalScale(temperature):1}><group ref={ref}><mesh geometry={geo} onClick={e=>{e.stopPropagation();set({selected:gear.module,piece:gear.id});}} onPointerOver={()=>{document.body.style.cursor='pointer';}} onPointerOut={()=>{document.body.style.cursor='auto';}}><meshStandardMaterial color={piece===gear.id?'#92e2e4':gear.connection==='external'?'#bd9055':'#ddbb79'} metalness={.8} roughness={.29} emissive={highlight?'#65522c':'#000000'} emissiveIntensity={.4} transparent={transparent} opacity={transparent?.55:1}/></mesh><mesh rotation={[Math.PI/2,0,0]} position={[0,0,.105]}><cylinderGeometry args={[.065,.065,.045,12]} /><meshStandardMaterial color="#293e46" metalness={.9} roughness={.25}/></mesh></group><mesh rotation={[Math.PI/2,0,0]} position={[0,0,-.36]}><cylinderGeometry args={[.047,.047,.8,12]}/><meshStandardMaterial color="#526b76" metalness={.85} roughness={.22}/></mesh></group>;
}
function Bolts(){const ref=useRef<THREE.InstancedMesh>(null);useEffect(()=>{const dummy=new THREE.Object3D();for(let i=0;i<96;i++){const a=i/96*Math.PI*2;dummy.position.set(7.07*Math.cos(a),7.07*Math.sin(a),-.47);dummy.rotation.set(Math.PI/2,0,0);dummy.updateMatrix();ref.current!.setMatrixAt(i,dummy.matrix);}ref.current!.instanceMatrix.needsUpdate=true;},[]);return <instancedMesh ref={ref} args={[undefined,undefined,96]}><cylinderGeometry args={[.045,.045,.06,6]}/><meshStandardMaterial color="#e1ca92" metalness={.9} roughness={.3}/></instancedMesh>;}
function LunarDevice(){const k1=useRef<THREE.Group>(null),k2=useRef<THREE.Group>(null);useFrame(()=>{const theta=(134.9633964+360*(useMachine.getState().jd-J2000)/27.55455)*Math.PI/180;if(k1.current)k1.current.rotation.z=theta;if(k2.current)k2.current.rotation.z=pinSlot(theta);});return <group position={[0,-.45,1.05]} scale={.68}><group ref={k1}><mesh><ringGeometry args={[.87,1,64]}/><meshStandardMaterial color="#e3c188" metalness={.75} side={THREE.DoubleSide}/></mesh><mesh position={[1,0,.1]}><sphereGeometry args={[.09,12,12]}/><meshStandardMaterial color="#c1efff" emissive="#75c8db" emissiveIntensity={1}/></mesh></group><group position={[.1098,0,.12]} ref={k2}><mesh position={[.52,.06,0]}><boxGeometry args={[1.2,.035,.04]}/><meshStandardMaterial color="#82c7cd"/></mesh><mesh position={[.52,-.06,0]}><boxGeometry args={[1.2,.035,.04]}/><meshStandardMaterial color="#82c7cd"/></mesh></group></group>;}
function Armillary(){const ref=useRef<THREE.Group>(null);useFrame(()=>{if(ref.current)ref.current.rotation.z=angleAt(useMachine.getState().jd,365.2425,{n:1,d:1});});return <group position={[0,0,1]}><group ref={ref}><mesh rotation={[.5,.3,0]}><torusGeometry args={[1.55,.032,12,128]}/><meshStandardMaterial color="#d2b878" metalness={.85} roughness={.25}/></mesh><mesh rotation={[1.1,-.6,0]}><torusGeometry args={[1.43,.046,12,128]}/><meshStandardMaterial color="#bfa271" metalness={.85} roughness={.25}/></mesh><mesh rotation={[.6,1.2,0]}><torusGeometry args={[1.31,.023,12,96]}/><meshStandardMaterial color="#74abb7" metalness={.75} roughness={.3}/></mesh><mesh><sphereGeometry args={[.64,40,32]}/><meshStandardMaterial color="#193a50" roughness={.32} metalness={.65}/></mesh><mesh><sphereGeometry args={[.647,16,12]}/><meshBasicMaterial color="#94b4b5" wireframe transparent opacity={.22}/></mesh></group><LunarDevice/></group>;}
function Clockwork(){const {selected,isolate,exploded,cutaway,transparent,quality,night}=useMachine(useShallow(s=>({selected:s.selected,isolate:s.isolate,exploded:s.exploded,cutaway:s.cutaway,transparent:s.transparent,quality:s.quality,night:s.night})));const texture=useMemo(dialTexture,[]);const {gl}=useThree();useEffect(()=>{gl.localClippingEnabled=true;},[gl]);
 return <group><mesh position={[0,0,-1]}><circleGeometry args={[7.38,128]}/><meshStandardMaterial map={texture} metalness={.55} roughness={.55} transparent opacity={transparent?.23:.97} side={THREE.DoubleSide} clippingPlanes={cutaway?[new THREE.Plane(new THREE.Vector3(1,0,0),0)]:[]}/></mesh>{[7.48,7.36,6.48,2.03,1.92].map((r,i)=><mesh key={r} position={[0,0,-.7+i*.03]}><torusGeometry args={[r,i<2?.055:.022,12,160]}/><meshStandardMaterial color={i%2?'#637e81':'#b89760'} metalness={.85} roughness={.34}/></mesh>)}<Bolts/>
 {[...Array(7)].map((_,i)=><mesh key={'shaft'+i} rotation={[Math.PI/2,0,0]} position={[0,0,-1.5]}><cylinderGeometry args={[.12+i*.082,.12+i*.082,2.5-i*.18,48,1,true]}/><meshStandardMaterial color="#294554" metalness={.95} roughness={.22} side={THREE.DoubleSide}/></mesh>)}
 {[0,1,2,3].map(i=>{const a=Math.PI/4+i*Math.PI/2;return <group key={'support'+i} position={[6.7*Math.cos(a),6.7*Math.sin(a),-1.45]}><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.11,.16,1.6,16]}/><meshStandardMaterial color="#ab8553" metalness={.85} roughness={.35}/></mesh><mesh position={[0,0,-.75]}><boxGeometry args={[.45,.45,.12]}/><meshStandardMaterial color="#684c32" metalness={.7}/></mesh></group>;})}
 {[...Array(7)].map((_,i)=><mesh key={i} position={[0,0,-.6-i*.08]}><torusGeometry args={[.12+i*.082,.033,10,48]}/><meshStandardMaterial color="#506a78" metalness={.95} roughness={.25}/></mesh>)}
 {modules.map((m,mi)=>{if(isolate&&selected!==m.id)return null;const p=centers[mi];return <group key={m.id} position={[p[0]*(exploded?1.13:1),p[1]*(exploded?1.13:1),selected===m.id&&exploded?1.5:0]}>
 <mesh position={[0,0,-.75]}><circleGeometry args={[1.48,48]}/><meshStandardMaterial color={selected===m.id?'#193e4a':'#10232b'} metalness={.5} roughness={.55} transparent opacity={transparent?.2:1}/></mesh><mesh position={[0,0,-.58]}><torusGeometry args={[1.5,.023,10,64]}/><meshStandardMaterial color={selected===m.id?'#9bdce0':'#8a754b'} emissive={selected===m.id?'#244b50':'#000'} metalness={.65}/></mesh>
 {gears.filter(g=>g.module===m.id&&(quality!=='baja'||g.depth===0)&&(!cutaway||g.depth<2)).map(g=><group key={g.id} position={[0,0,exploded?-g.depth*.42:0]}><GearMesh gear={g} highlight={selected===m.id}/></group>)}
 <mesh position={[0,-1.23,0]}><boxGeometry args={[.38,.06,.06]}/><meshBasicMaterial color={m.color}/></mesh>
 </group>})}<Armillary/><ModuleInstrument/>
 {night&&<><Line points={Array.from({length:129},(_,i)=>{const a=i/128*Math.PI*2;return [8.05*Math.cos(a),8.05*Math.sin(a)*.36,.8] as [number,number,number];})} color="#376678" lineWidth={1}/><Line points={[[-8,0,.7],[8,0,.7]]} color="#274b5e" lineWidth={1}/></>}
 </group>;
}
function CameraControl(){const view=useMachine(s=>s.view),{camera}=useThree();const controls=useRef<any>(null);useEffect(()=>{const p=view==='frontal'?[0,0,21]:view==='lateral'?[16,0,9]:[0,-7.4,20];camera.position.set(...p as [number,number,number]);controls.current?.target.set(0,0,0);controls.current?.update();},[view,camera]);return <OrbitControls ref={controls} makeDefault minDistance={4} maxDistance={36} enableDamping dampingFactor={.08}/>;}
class SceneBoundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<div className="scene-fallback"><h2>Modo de lecturas</h2><p>WebGL no está disponible. Los motores y controles temporales siguen operativos.</p></div>:this.props.children;}}
function RefreshScene(){const invalidate=useThree(s=>s.invalidate);useEffect(()=>useMachine.subscribe(()=>invalidate()),[invalidate]);return null;}
export default function Machine(){const {quality,night}=useMachine(useShallow(s=>({quality:s.quality,night:s.night})));return <SceneBoundary><Canvas frameloop="demand" gl={{antialias:quality!=='baja',preserveDrawingBuffer:true,powerPreference:quality==='baja'?'low-power':'high-performance'}} dpr={quality==='baja'?1:quality==='ceremonial'?[1,2]:[1,1.5]} camera={{position:[0,-7.4,20],fov:46}}><color attach="background" args={[night?'#09151b':'#283a40']}/><ambientLight intensity={night?.9:1.5}/><directionalLight position={[-5,7,12]} intensity={3.2} color="#fff0ce"/><directionalLight position={[5,-3,6]} intensity={2} color="#78bbd1"/><pointLight position={[0,0,6]} intensity={32} color="#dcaa55"/>{quality!=='baja'&&<Stars radius={70} depth={25} count={quality==='ceremonial'?3500:1200} factor={2} saturation={0} fade speed={0}/>}<Suspense fallback={null}><Clockwork/></Suspense><RefreshScene/><CameraControl/><GizmoHelper alignment="bottom-right" margin={[45,50]}><GizmoViewport axisColors={['#b58261','#9fbc92','#85b4d5']} labelColor="#0b1720"/></GizmoHelper></Canvas></SceneBoundary>;}
