import { create } from 'zustand';
import { nowJD, toJD, J2000, type Calendar } from './time';
import {MAX_DAYS} from '../wheel/engine';
export const moduleIds=['lunar','maya','sino','yijing','vedic','egypt','kalachakra'] as const;
export type ModuleId=typeof moduleIds[number];
export interface Settings {jd:number;d:number;calendar:Calendar;place:string;latitude:number;longitude:number;altitude:number;zone:string;speed:number;playing:boolean;selected:ModuleId;piece:string|null;quality:'baja'|'media'|'alta'|'ceremonial';exploded:boolean;transparent:boolean;cutaway:boolean;isolate:boolean;night:boolean;contrast:boolean;hidden:boolean;sound:boolean;view:'perspectiva'|'frontal'|'lateral';backlash:number;temperature:number;loss:number;torqueLimit:number;physics:boolean;correlation:number;sidereal:boolean;ayanamsa:'lahiri'|'fagan'|'none';dayBoundary:'sunrise'|'midnight';birth:string;birthPlace:string;birthZone:string;birthLatitude:number;birthLongitude:number;hexagram:number;yijingRule:'none'|'binary-demo-v1';siriusAltitude:number;solarDepression:number;horizon:number;cosmicExponent:number;}
const initialNow = nowJD();
export const defaults:Settings={jd:initialNow,d:initialNow-J2000,calendar:'gregorian',place:'Ciudad de México',latitude:19.4326,longitude:-99.1332,altitude:2240,zone:'America/Mexico_City',speed:1,playing:false,selected:'lunar',piece:null,quality:'media',exploded:false,transparent:false,cutaway:false,isolate:false,night:false,contrast:false,hidden:false,sound:false,view:'perspectiva',backlash:0,temperature:20,loss:.02,torqueLimit:20,physics:false,correlation:584283,sidereal:true,ayanamsa:'lahiri',dayBoundary:'sunrise',birth:'1990-01-01 12:00:00',birthPlace:'Ciudad de México',birthZone:'America/Mexico_City',birthLatitude:19.4326,birthLongitude:-99.1332,hexagram:0,yijingRule:'binary-demo-v1',siriusAltitude:3,solarDepression:8,horizon:0,cosmicExponent:9};
const enums:Partial<Record<keyof Settings,readonly unknown[]>>={calendar:['gregorian','julian'],selected:moduleIds,quality:['baja','media','alta','ceremonial'],view:['perspectiva','frontal','lateral'],ayanamsa:['lahiri','fagan','none'],dayBoundary:['sunrise','midnight'],yijingRule:['none','binary-demo-v1']};
export function validateState(raw:unknown):Settings{
 const obj=raw as {version?:number;state?:Record<string,unknown>};if(!obj||obj.version!==1||!obj.state)throw Error('Formato incompatible: se requiere versión 1.');
 const s={...defaults};for(const key of Object.keys(defaults) as (keyof Settings)[]){const v=obj.state[key];if(v===undefined)continue;if(key==='piece'){if(v!==null&&typeof v!=='string')throw Error('Pieza inválida');}else if(typeof v!==typeof defaults[key]||(typeof v==='number'&&!Number.isFinite(v)))throw Error(`Campo inválido: ${key}`);if(enums[key]&&!enums[key]!.includes(v))throw Error(`Opción inválida: ${key}`);Object.assign(s,{[key]:v});}
 s.d=s.jd-J2000;
 const ranges:Partial<Record<keyof Settings,[number,number]>>={jd:[J2000-MAX_DAYS,J2000+MAX_DAYS],d:[-MAX_DAYS,MAX_DAYS],latitude:[-90,90],longitude:[-180,180],altitude:[-500,10000],speed:[-1e12,1e12],backlash:[0,5],temperature:[-50,100],loss:[0,.5],torqueLimit:[0,100],correlation:[0,3000000],hexagram:[0,63],birthLatitude:[-90,90],birthLongitude:[-180,180],siriusAltitude:[0,20],solarDepression:[1,18],horizon:[0,20],cosmicExponent:[0,22]};
 for(const [k,[min,max]]of Object.entries(ranges)){const n=s[k as keyof Settings] as number;if(n<min||n>max)throw Error(`Fuera de rango: ${k}`);}
 if(!Number.isInteger(s.correlation)||!Number.isInteger(s.hexagram))throw Error('Correlación y hexagrama deben ser enteros');
 new Intl.DateTimeFormat('es',{timeZone:s.zone});new Intl.DateTimeFormat('es',{timeZone:s.birthZone});
 return s;
}
export const serialize=(s:Settings)=>JSON.stringify({version:1,state:Object.fromEntries(Object.keys(defaults).map(k=>[k,s[k as keyof Settings]]))},null,2);
function restore(){if(typeof window==='undefined')return defaults;try{const raw=localStorage.getItem('machina-v1');return raw?{...validateState(JSON.parse(raw)),playing:false,hidden:false}:defaults;}catch{return defaults;}}
export const useMachine=create<Settings & {set:(patch:Partial<Settings>)=>void;reset:()=>void;now:()=>void}>((set)=>({...restore(),set:(patch:Partial<Settings>)=>{const nextPatch={...patch};if(nextPatch.jd!==undefined&&nextPatch.d===undefined){nextPatch.d=nextPatch.jd-J2000;}else if(nextPatch.d!==undefined&&nextPatch.jd===undefined){nextPatch.jd=nextPatch.d+J2000;}set(nextPatch);},reset:()=>set({...defaults}),now:()=>{const jd=nowJD();set({jd,d:jd-J2000,playing:false});}}));
let timer:ReturnType<typeof setTimeout>;useMachine.subscribe(s=>{clearTimeout(timer);timer=setTimeout(()=>{try{localStorage.setItem('machina-v1',serialize(s));}catch{/* storage unavailable: session remains usable */}},250);});
